#Service que expoe mongodb para outros services
apiVersion: v1
kind: Service
metadata:
  name: mongodb  # DNS name
  labels:
    app: mongodb
    tier: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector: # mongodb Pod Should contain same labels
    app: mongodb
    tier: database
  type: NodePort
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: database
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: database
  serviceName: "mongodb"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo
          name: mongodb
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /var/lib/mongodb
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: volume-mongodb